FROM alpine:latest

RUN apk add --no-cache sqlite bash tzdata tar gzip coreutils findutils rclone python3 py3-openpyxl

COPY scripts/backup.sh /usr/local/bin/backup.sh
COPY scripts/entrypoint.sh /usr/local/bin/entrypoint.sh
COPY scripts/export_excel.py /usr/local/bin/export_excel.py

RUN chmod +x /usr/local/bin/backup.sh /usr/local/bin/entrypoint.sh /usr/local/bin/export_excel.py

ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]
